replicaCount: 1

image:
  repository: 352383909524.dkr.ecr.eu-central-1.amazonaws.com/test-deploy
  tag: "v1.1.0"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30082

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Dev-specific settings
environment: development
debug: true 