replicaCount: 1

image:
  repository: 352383909524.dkr.ecr.eu-central-1.amazonaws.com/test-deploy
  tag: "v1.0.0"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Prod-specific settings
environment: production
debug: false 